language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - docker
env:
  matrix:
    - MODULE=!querydsl-scala PROFILES=all,travis,examples
    - MODULE=!querydsl-jpa-codegen PROFILES=jpa,hibernate5,travis,examples
    - MODULE=querydsl-scala PROFILES=all,travis
install:
  - ./mvnw -B -q --projects ${MODULE} -P${PROFILES} install -DskipTests=true
before_script:
  - ./travis/docker_bootstrap.sh
script:
  - docker ps
  - ./mvnw -B test -P${PROFILES} --projects ${MODULE} jacoco:report
sudo: required
after_success:
  - ./mvnw coveralls:report
cache:
  directories:
    - $HOME/.m2
